In [1]:
import utils
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

%matplotlib inline

In [2]:
train_loader, test_loader = utils.mnist()

Train mean and std tensor([0.1307]) tensor([0.3015])
Test mean and std tensor([0.1325]) tensor([0.3039])


In [3]:
batch_x, batch_y = next(iter(train_loader))
print(batch_x.shape, batch_y.shape)

torch.Size([50, 1, 28, 28]) torch.Size([50])


In [4]:
flatten_x = batch_x.view(-1, 784)
print(flatten_x.shape)

torch.Size([50, 784])


In [5]:
layer = nn.Linear(784, 10)
print([p.shape for p in layer.parameters()])
params = [p for p in layer.parameters()]
print(params[1])

[torch.Size([10, 784]), torch.Size([10])]
Parameter containing:
tensor([-0.0275,  0.0146, -0.0179, -0.0040,  0.0099, -0.0192,  0.0093,  0.0089,
         0.0285, -0.0292], requires_grad=True)


In [6]:
hidden_x = layer(flatten_x)
print(hidden_x.shape, hidden_x[0][:10])

torch.Size([50, 10]) tensor([-0.4739, -0.4003, -0.0805, -0.8000, -0.5274,  0.3682,  0.1847, -0.3737,
        -0.0875, -1.2968], grad_fn=<SliceBackward>)


In [7]:
rectified = F.relu(hidden_x)
print(hidden_x[0])
print(rectified[0])

tensor([-0.4739, -0.4003, -0.0805, -0.8000, -0.5274,  0.3682,  0.1847, -0.3737,
        -0.0875, -1.2968], grad_fn=<SelectBackward>)
tensor([0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.3682, 0.1847, 0.0000, 0.0000,
        0.0000], grad_fn=<SelectBackward>)
