In [1]:
import utils
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

%matplotlib inline

In [2]:
train_loader, test_loader = utils.mnist()

60000
Train mean and std tensor([0.1307]) tensor([0.3015])


In [3]:
batch_x, batch_y = next(iter(train_loader))
print(batch_x.shape, batch_y.shape)

torch.Size([50, 1, 28, 28]) torch.Size([50])


In [4]:
flatten_x = batch_x.view(-1, 784)
print(flatten_x.shape)

torch.Size([50, 784])


In [5]:
layer = nn.Linear(784, 10)
print([p.shape for p in layer.parameters()])
params = [p for p in layer.parameters()]
print(params[1])

[torch.Size([10, 784]), torch.Size([10])]
Parameter containing:
tensor([ 0.0066, -0.0313,  0.0002, -0.0141,  0.0132, -0.0062,  0.0221,  0.0062,
        -0.0024, -0.0107], requires_grad=True)


In [6]:
hidden_x = layer(flatten_x)
print(hidden_x.shape, hidden_x[0][:10])

torch.Size([50, 10]) tensor([ 0.1848, -0.1924, -0.2471, -0.2415,  0.4214,  0.5822, -0.5378,  0.3605,
        -0.5112,  0.0111], grad_fn=<SliceBackward>)


In [7]:
rectified = F.relu(hidden_x)
print(hidden_x[0])
print(rectified[0])

tensor([ 0.1848, -0.1924, -0.2471, -0.2415,  0.4214,  0.5822, -0.5378,  0.3605,
        -0.5112,  0.0111], grad_fn=<SelectBackward>)
tensor([0.1848, 0.0000, 0.0000, 0.0000, 0.4214, 0.5822, 0.0000, 0.3605, 0.0000,
        0.0111], grad_fn=<SelectBackward>)
