In [1]:
import utils
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

%matplotlib inline

In [2]:
train_loader, test_loader = utils.mnist()

In [3]:
batch_x, batch_y = next(iter(train_loader))
print(batch_x.shape, batch_y.shape)

tensor(8.2869e-09) tensor(1.0000)
tensor(-4.9417e-09) tensor(1.)
tensor(3.3376e-08) tensor(1.)
tensor(9.8074e-09) tensor(1.)
tensor(2.3568e-09) tensor(1.)
tensor(3.9610e-08) tensor(1.)
tensor(2.7978e-08) tensor(1.0000)
tensor(6.0213e-08) tensor(1.)
tensor(2.8586e-08) tensor(1.)
tensor(2.4100e-08) tensor(1.0000)
tensor(-1.6422e-08) tensor(1.)
tensor(4.8125e-08) tensor(1.)
tensor(6.3862e-09) tensor(1.0000)
tensor(1.7106e-08) tensor(1.)
tensor(-2.4100e-08) tensor(1.0000)
tensor(-2.8966e-08) tensor(1.)
tensor(3.3452e-09) tensor(1.0000)
tensor(1.3609e-08) tensor(1.)
tensor(-2.0451e-08) tensor(1.)
tensor(-9.1992e-09) tensor(1.)
tensor(2.7369e-08) tensor(1.)
tensor(5.6031e-08) tensor(1.)
tensor(2.6609e-09) tensor(1.)
tensor(1.0644e-09) tensor(1.0000)
tensor(5.0862e-08) tensor(1.)
tensor(-5.8464e-08) tensor(1.0000)
tensor(1.7638e-08) tensor(1.0000)
tensor(-2.8054e-08) tensor(1.)
tensor(-4.4399e-08) tensor(1.)
tensor(-7.2149e-08) tensor(1.)
tensor(-1.4445e-08) tensor(1.)
tensor(-8.0892e-08) ten

In [4]:
flatten_x = batch_x.view(-1, 784)
print(flatten_x.shape)

torch.Size([50, 784])


In [5]:
layer = nn.Linear(784, 10)
print([p.shape for p in layer.parameters()])
params = [p for p in layer.parameters()]
print(params[1])

[torch.Size([10, 784]), torch.Size([10])]
Parameter containing:
tensor([-0.0338, -0.0343, -0.0316, -0.0285, -0.0233,  0.0087,  0.0271,  0.0212,
         0.0199,  0.0070], requires_grad=True)


In [6]:
hidden_x = layer(flatten_x)
print(hidden_x.shape, hidden_x[0][:10])

torch.Size([50, 10]) tensor([-0.0543,  0.4776,  0.3449, -0.2172, -0.1873,  0.1772, -0.3921, -0.4060,
         0.3323,  0.6677], grad_fn=<SliceBackward>)


In [7]:
rectified = F.relu(hidden_x)
print(hidden_x[0])
print(rectified[0])

tensor([-0.0543,  0.4776,  0.3449, -0.2172, -0.1873,  0.1772, -0.3921, -0.4060,
         0.3323,  0.6677], grad_fn=<SelectBackward>)
tensor([0.0000, 0.4776, 0.3449, 0.0000, 0.0000, 0.1772, 0.0000, 0.0000, 0.3323,
        0.6677], grad_fn=<SelectBackward>)
